version: "3.5"

services:
  api:
    container_name: dock-user
    image: dock-user:latest
    environment:
      DB_HOST: postgres
      DB_NAME: dockdatabase
    restart: always
    links:
      - postgres
    build:
      context: .
      target: backend
    ports:
      - 9090:9090
    networks:
      - proxynet
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - proxynet
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

networks:
  proxynet:
    name: internal-network