server:
  port: 9090
management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  boot:
    admin:
      client:
        url: http://${ADMIN_HOST:localhost:8061}
  application:
    name: dock-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:docktestdb}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rabbitmq:
  host: ${RABBIT_HOST:localhost}
  port: 5672
  password: ${RABBITMQ_DEFAULT_PASS:guest}
  username: ${RABBITMQ_DEFAULT_USER:guest}
  queues:
    controllerRequest:
      exchange: clientRequestFinesExchange
      queue: ru.vlpetko.client
      routingkey: ru.vlpetko.guest.client.rk